# Generated by Django 5.0.4 on 2024-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('profilepic', models.FileField(max_length=500, upload_to='')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('emailaddress', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('profilepic', models.FileField(max_length=500, upload_to='')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('emailaddress', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
            ],
        ),
    ]
