# Generated by Django 5.0.4 on 2024-07-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='profilepic',
            new_name='dprofilepic',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='profilepic',
            new_name='pprofilepic',
        ),
    ]
