# Generated by Django 5.0.4 on 2024-08-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(max_length=500, upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
    ]
