# Generated by Django 5.0.4 on 2024-08-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
