# Generated by Django 5.0.4 on 2024-08-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_rename_content_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
