# Generated by Django 5.0.4 on 2024-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0005_alter_blog_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.FileField(max_length=500, upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=15)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
